import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const failures=[],results=[],requests=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 page.on('pageerror',error=>failures.push(error.message));
 page.on('console',msg=>{if(msg.type()==='error')failures.push(msg.text());});
 page.on('response',response=>{if(response.status()>=400)failures.push(`${response.status()} ${response.url()}`);});
 page.on('request',request=>requests.push(request.url()));
 await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});
 await page.evaluate(()=>document.fonts.ready);
 await page.waitForFunction(()=>document.querySelector('canvas').dataset.frame==='0');
 assert.equal(await page.locator('audio[data-audio-origin="background"]').evaluate(el=>el.paused),true);
 await page.screenshot({path:'artifacts/desktop-hero.png'});
 const distance=await page.locator('.hero-scroll').evaluate(el=>el.offsetHeight-el.querySelector('.hero').offsetHeight);
 await page.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),distance*.5);
 await page.waitForFunction(()=>Number(document.querySelector('canvas').dataset.frame)>=47&&Number(document.querySelector('canvas').dataset.frame)<=52);
 results.push('Desktop scroll reaches middle frames.');
 await page.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),distance);
 await page.waitForFunction(()=>document.querySelector('canvas').dataset.frame==='99');
 await page.screenshot({path:'artifacts/desktop-scroll-end.png'});
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.waitForFunction(()=>document.querySelector('canvas').dataset.frame==='0');
 results.push('Sequence reaches frame 100 and reverses to frame 1.');
 await page.locator('#pillar-1').click();
 await page.locator('#pillar-1').press('ArrowRight');
 assert.equal(await page.locator('#pillar-2').getAttribute('aria-selected'),'true');
 await page.locator('#metodo').scrollIntoViewIfNeeded();
 await page.screenshot({path:'artifacts/desktop-method.png'});
 await page.getByRole('radio',{name:'Canto',exact:true}).check();
 await page.locator('#level').selectOption('Já tenho alguma experiência');
 await page.locator('#goal').fill('cantar rock com mais controle');
 const contact=new URL(await page.getByRole('link',{name:'Abrir conversa no WhatsApp',exact:true}).getAttribute('href'));
 assert.equal(contact.pathname,'/5521975769161');
 assert.match(contact.searchParams.get('text'),/Canto.*Já tenho alguma experiência.*cantar rock com mais controle/);
 results.push('Contact message correctly contains interest, level and goal; no message sent.');
 const singingFaq=page.getByRole('button',{name:/Também posso fazer aulas de canto/});
 await singingFaq.click();
 assert.equal(await singingFaq.getAttribute('aria-expanded'),'true');
 await page.getByRole('button',{name:'Ativar som de fundo',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('audio').paused);
 await page.locator('.performance-player').scrollIntoViewIfNeeded();
 assert.equal(await page.getByRole('button',{name:'Pausar trilha'}).count(),2);
 await page.getByRole('button',{name:'Pausar trilha'}).first().click();
 await page.waitForFunction(()=>document.querySelector('audio').paused);
 await page.getByRole('button',{name:'Reproduzir trilha'}).first().click();
 await page.waitForFunction(()=>!document.querySelector('audio').paused);
 assert.equal(await page.locator('video').count(),0);
 assert.equal(requests.some(url=>/\.mp4(?:$|\?)/i.test(url)),false);
 results.push('One shared supplied audio track powers both controls; no MP4 element or request is present.');
 const brokenAnchors=await page.locator('a[href^="#"]').evaluateAll(links=>links.filter(a=>!document.getElementById(a.getAttribute('href').slice(1))).map(a=>a.outerHTML));
 assert.deepEqual(brokenAnchors,[]);
 results.push('All internal anchor targets exist.');
 for(const width of [1440,768,390,320]) {
  await page.setViewportSize({width,height:844});
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  assert.equal(overflow,false,`horizontal overflow at ${width}`);
  if(width===390){
   await page.waitForFunction(()=>[...document.querySelectorAll('.hero-scene')].every(el=>getComputedStyle(el).opacity===(el.classList.contains('is-hidden')?'0':'1')));
   const heroTitle=await page.locator('.hero-scene h1').boundingBox();
   assert.ok(heroTitle && heroTitle.y>=68,'mobile hero title is obscured by the header');
   await page.screenshot({path:'artifacts/mobile-hero.png'});
   await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
   assert.equal(await page.locator('#mobile-menu').isVisible(),true);
   await page.keyboard.press('Escape');
   assert.equal(await page.locator('#mobile-menu').count(),0);
   await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
   await page.getByRole('navigation',{name:'Navegação móvel'}).getByRole('link',{name:'Aulas',exact:true}).click();
   assert.equal(await page.locator('#mobile-menu').count(),0);
   await page.screenshot({path:'artifacts/mobile-lessons.png'});
  }
 results.push(`No horizontal overflow at ${width}px.`);
 }
 await page.setViewportSize({width:1440,height:900});
 await page.locator('.guitar-horizon').scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>document.querySelector('.guitar-horizon-canvas')?.dataset.frame!==undefined);
 const guitarDistance=await page.locator('.guitar-horizon').evaluate(el=>el.offsetHeight-el.querySelector('.guitar-horizon-stage').offsetHeight);
 const guitarTop=await page.locator('.guitar-horizon').evaluate(el=>el.getBoundingClientRect().top+scrollY);
 await page.evaluate(({top,distance})=>window.scrollTo({top:top+distance*.6,behavior:'instant'}),{top:guitarTop,distance:guitarDistance});
 await page.waitForFunction(()=>Number(document.querySelector('.guitar-horizon-canvas')?.dataset.frame)>=50);
 results.push('The guitar transition reaches later frames before the method section.');
 const mobile=await browser.newContext({viewport:{width:390,height:844}});
 const mobilePage=await mobile.newPage();
 const mobileFrameRequests=[];mobilePage.on('request',r=>{if(/\/(?:guitar-)?frames(?:-mobile)?\//.test(r.url()))mobileFrameRequests.push(r.url());});
 await mobilePage.goto('http://localhost:5173/',{waitUntil:'networkidle'});
 assert.equal(await mobilePage.locator('.hero-scroll').evaluate(el=>el.classList.contains('is-static')),true);
 assert.equal(await mobilePage.locator('.hero-scroll').evaluate(el=>el.offsetHeight),844);
 await mobilePage.screenshot({path:'artifacts/mobile-hero.png'});
 assert.equal(mobileFrameRequests.length,0);
 results.push('Mobile uses static art direction with no frame decoding during scrolling.');
 await mobile.close();
 const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
 const reducedPage=await reduced.newPage();
 const frameRequests=[];reducedPage.on('request',r=>{if(/\/(?:guitar-)?frames(?:-mobile)?\//.test(r.url()))frameRequests.push(r.url());});
 await reducedPage.goto('http://localhost:5173/',{waitUntil:'networkidle'});
 assert.equal(await reducedPage.locator('.hero-scroll').evaluate(el=>el.classList.contains('is-static')),true);
 assert.equal(await reducedPage.locator('.hero-scroll').evaluate(el=>el.offsetHeight),844);
 assert.equal(await reducedPage.locator('.guitar-horizon').evaluate(el=>el.classList.contains('is-static')),true);
 assert.equal(frameRequests.length,0);
 results.push('Reduced-motion preference removes pinned distance and frame downloads.');
 await reduced.close();
 assert.deepEqual(failures,[]);
 results.push('No browser errors or failed HTTP responses.');
 console.log(JSON.stringify({passed:results.length,results},null,2));
 await writeFile('artifacts/qa-results.json',JSON.stringify({passed:results.length,results,failures},null,2));
} catch(error) {console.error(error);process.exitCode=1;await writeFile('artifacts/qa-failure.txt',`${error.stack}\n${failures.join('\n')}`)}
finally {await browser.close();}
